using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LayoutObserver.Generator;

/// <summary>Emits typed field access: reflection metadata and dynamic IL are not used by probes.</summary>
[Generator]
public sealed class LayoutProbeGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidRegistration = new DiagnosticDescriptor(
        "LAYOUT001", "Invalid layout registration", "{0}", "LayoutObserver", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var input = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.Configuration", out string? configuration);
            return configuration;
        }));
        context.RegisterSourceOutput(input, (production, pair) => Execute(production, pair.Left, pair.Right));
    }

    private static void Execute(SourceProductionContext context, Compilation compilation, string? configuration)
    {
        var registrations = new List<(INamedTypeSymbol Type, string Id)>();
        var ids = new HashSet<string>(StringComparer.Ordinal);
        foreach (AttributeData attribute in compilation.Assembly.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != "LayoutObserver.Managed.ObserveLayoutAttribute") continue;
            if (attribute.ConstructorArguments.Length != 2 ||
                !(attribute.ConstructorArguments[0].Value is INamedTypeSymbol type) ||
                !(attribute.ConstructorArguments[1].Value is string id) || string.IsNullOrWhiteSpace(id) || !ids.Add(id))
            {
                context.ReportDiagnostic(Diagnostic.Create(InvalidRegistration, Location.None,
                    "ObserveLayout requires a type and a unique nonempty observation ID."));
                continue;
            }
            registrations.Add((type, id));
        }

        var emitted = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var registry = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace LayoutObserver.Managed {\ninternal static class GeneratedProbeRegistry {\n");
        registry.Append("public const string CompilerVersion = ").Append(Literal(typeof(CSharpCompilation).Assembly.GetName().Version?.ToString() ?? "unknown")).Append(";\n");
        registry.Append("public const string BuildConfiguration = ").Append(Literal(configuration ?? "unknown")).Append(";\n");
        registry.Append("public static global::System.Collections.Generic.IReadOnlyList<global::LayoutObserver.Managed.ProbeResult> Capture() {\nreturn new global::LayoutObserver.Managed.ProbeResult[] {\n");
        int index = 0;
        foreach (var registration in registrations)
        {
            INamedTypeSymbol type = registration.Type;
            string qualified = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string? reason = UnsupportedReason(type);
            if (reason != null)
            {
                registry.Append("global::LayoutObserver.Managed.ProbeMeasurements.Unsupported(")
                    .Append(Literal(registration.Id)).Append(", ").Append(Literal(qualified)).Append(", ")
                    .Append(Literal(reason)).Append("),\n");
                continue;
            }
            if (type.TypeKind == TypeKind.Enum || IsPrimitive(type.SpecialType))
            {
                registry.Append("global::LayoutObserver.Managed.ProbeMeasurements.ScalarValue<")
                    .Append(qualified).Append(">(").Append(Literal(registration.Id)).Append("),\n");
                continue;
            }

            INamedTypeSymbol definition = type.OriginalDefinition;
            bool partial = IsPartial(definition);
            string method = "__LayoutObserverCapture";
            if (partial)
            {
                if (emitted.Add(definition))
                    context.AddSource("LayoutProbe.Partial." + index++ + ".g.cs", SourceText.From(EmitPartial(definition), Encoding.UTF8));
                registry.Append(qualified).Append('.').Append(method).Append('(').Append(Literal(registration.Id)).Append("),\n");
            }
            else
            {
                string helper = "__LayoutObserverExternal" + index++;
                context.AddSource(helper + ".g.cs", SourceText.From(EmitExternal(type, helper), Encoding.UTF8));
                registry.Append("global::LayoutObserver.Managed.").Append(helper).Append('.').Append(method)
                    .Append('(').Append(Literal(registration.Id)).Append("),\n");
            }
        }
        registry.Append("};\n}\n}\n}\n");
        context.AddSource("GeneratedProbeRegistry.g.cs", SourceText.From(registry.ToString(), Encoding.UTF8));
    }

    private static string? UnsupportedReason(INamedTypeSymbol type)
    {
        if (type.TypeKind != TypeKind.Struct && type.TypeKind != TypeKind.Enum) return "static-probe-requires-value-type";
        if (type.IsRefLikeType) return "ref-like-values-cannot-have-array-stride";
        if (type.IsUnboundGenericType || type.TypeArguments.Any(t => t.TypeKind == TypeKind.TypeParameter)) return "open-generic-type";
        if (type.ContainingType != null) return "nested-type-requires-explicit-adapter";
        return null;
    }

    private static bool IsPartial(INamedTypeSymbol type) => type.DeclaringSyntaxReferences.Any(reference =>
        reference.GetSyntax() is TypeDeclarationSyntax syntax && syntax.Modifiers.Any(SyntaxKind.PartialKeyword));

    private static bool IsPrimitive(SpecialType type) => type == SpecialType.System_Boolean || type == SpecialType.System_Char ||
        type == SpecialType.System_SByte || type == SpecialType.System_Byte || type == SpecialType.System_Int16 ||
        type == SpecialType.System_UInt16 || type == SpecialType.System_Int32 || type == SpecialType.System_UInt32 ||
        type == SpecialType.System_Int64 || type == SpecialType.System_UInt64 || type == SpecialType.System_Single ||
        type == SpecialType.System_Double || type == SpecialType.System_IntPtr || type == SpecialType.System_UIntPtr;

    private static string EmitPartial(INamedTypeSymbol type)
    {
        var code = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        if (!type.ContainingNamespace.IsGlobalNamespace) code.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).Append(" {\n");
        if (type.IsReadOnly) code.Append("readonly ");
        code.Append(type.IsRecord ? "partial record struct " : "partial struct ").Append(Escape(type.Name));
        if (type.TypeParameters.Length > 0) code.Append('<').Append(string.Join(",", type.TypeParameters.Select(t => Escape(t.Name)))).Append('>');
        code.Append(" {\n").Append(EmitMethod(type, true)).Append("}\n");
        if (!type.ContainingNamespace.IsGlobalNamespace) code.Append("}\n");
        return code.ToString();
    }

    private static string EmitExternal(INamedTypeSymbol type, string helper) =>
        "// <auto-generated/>\n#nullable enable\nnamespace LayoutObserver.Managed { internal static class " + helper + " {\n" + EmitMethod(type, false) + "}\n}\n";

    private static string EmitMethod(INamedTypeSymbol type, bool inside)
    {
        string qualified = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var code = new StringBuilder("public static global::LayoutObserver.Managed.ProbeResult __LayoutObserverCapture(string id) {\n");
        IFieldSymbol[] fields = type.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic).ToArray();
        if (fields.Length > 0) code.Append(qualified).Append(" value = default;\n_ = value;\n");
        code.Append("var fields = new global::LayoutObserver.Managed.ProbeField[] {\n");
        foreach (IFieldSymbol field in fields)
        {
            string? reason = null;
            if (field.IsImplicitlyDeclared) reason = "compiler-generated-field-requires-explicit-adapter";
            else if (field.IsFixedSizeBuffer || field.Type.TypeKind == TypeKind.Pointer || field.Type.TypeKind == TypeKind.FunctionPointer)
                reason = "pointer-or-fixed-buffer-requires-explicit-adapter";
            else if (!inside && field.DeclaredAccessibility != Accessibility.Public &&
                     !(field.DeclaredAccessibility == Accessibility.Internal && type.DeclaringSyntaxReferences.Length > 0)) reason = "field-not-accessible-to-static-probe";
            if (reason != null)
            {
                code.Append("global::LayoutObserver.Managed.ProbeMeasurements.UnavailableField(")
                    .Append(Literal(field.Name)).Append(", ").Append(Literal(field.Type.ToDisplayString())).Append(", ")
                    .Append(Literal(reason)).Append("),\n");
                continue;
            }
            code.Append("global::LayoutObserver.Managed.ProbeMeasurements.Field(ref value, in value.")
                .Append(Escape(field.Name)).Append(", ").Append(Literal(field.Name));
            AttributeData? inline = (field.Type as INamedTypeSymbol)?.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "System.Runtime.CompilerServices.InlineArrayAttribute");
            if (inline != null && inline.ConstructorArguments.Length == 1 && inline.ConstructorArguments[0].Value is int length)
            {
                IFieldSymbol? element = ((INamedTypeSymbol)field.Type).GetMembers().OfType<IFieldSymbol>().FirstOrDefault(f => !f.IsStatic);
                if (element != null)
                {
                    code.Append(", global::LayoutObserver.Managed.ProbeMeasurements.InlineArray<")
                        .Append(field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(", ")
                        .Append(element.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(">(").Append(length).Append(')');
                    code.Append(", global::LayoutObserver.Managed.ProbeMeasurements.InlineValue<")
                        .Append(field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(", ")
                        .Append(element.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(">(").Append(length)
                        .Append(", new global::LayoutObserver.Managed.ProbeField[] {\n");
                    for (int elementIndex = 0; elementIndex < length; elementIndex++)
                        code.Append("global::LayoutObserver.Managed.ProbeMeasurements.Field(ref global::System.Runtime.CompilerServices.Unsafe.AsRef(in value.").Append(Escape(field.Name))
                            .Append("), in value.").Append(Escape(field.Name)).Append('[').Append(elementIndex).Append("], ")
                            .Append(Literal(elementIndex.ToString(System.Globalization.CultureInfo.InvariantCulture))).Append("),\n");
                    code.Append("})");
                }
            }
            code.Append("),\n");
        }
        code.Append("};\nreturn global::LayoutObserver.Managed.ProbeMeasurements.Value<").Append(qualified)
            .Append(">(id, typeof(").Append(qualified).Append(").ToString(), fields);\n}\n");
        return code.ToString();
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);
    private static string Escape(string value) => "@" + value;
}
