// AUTO-GENERATED by Boost.TypeLayout Signature Export Tool
// Platform: unit_producer_packed (unit_producer_packed)
// Generated: 2026-08-31T13:20:51Z
//
// This file contains constexpr signature data.

#ifndef BOOST_TYPELAYOUT_SIG_UNIT_PRODUCER_PACKED_HPP
#define BOOST_TYPELAYOUT_SIG_UNIT_PRODUCER_PACKED_HPP

#include <boost/typelayout/tools/sig_types.hpp>

namespace boost { namespace typelayout { namespace platform {
namespace unit_producer_packed {

// ---- Platform Metadata ----

inline constexpr const char platform_name[] = "unit_producer_packed";
inline constexpr const char arch_prefix[] = "[64-le]";
inline constexpr std::size_t pointer_size      = 8;
inline constexpr std::size_t sizeof_long        = 8;
inline constexpr std::size_t sizeof_wchar_t     = 4;
inline constexpr std::size_t sizeof_long_double = 16;
inline constexpr std::size_t max_align          = 16;
inline constexpr const char data_model[]        = "LP64";

// ---- Type Signatures ----

// --- UnitSnapshot ---
inline constexpr const char UnitSnapshot_layout[] =
    "[64-le]record[s:72,a:8]{@0:u64[s:8,a:8],@8:u64[s:8,a:8],@16:u64[s:8,a:8],@24:i32[s:4,a:4],@28:i32[s:4,a:4],@32:i32[s:4,a:4],@36:u32[s:4,a:4],@40:u32[s:4,a:4],@44:u32[s:4,a:4],@48:u32[s:4,a:4],@52:u32[s:4,a:4],@56:u32[s:4,a:4],@60:u32[s:4,a:4],@64:u32[s:4,a:4],@68:u32[s:4,a:4]}";
inline constexpr bool UnitSnapshot_byte_copy_safe = true;

// --- Effect ---
inline constexpr const char Effect_layout[] =
    "[64-le]record[s:21,a:1]{@0:u32[s:4,a:4],@4:enum[s:1,a:1]<u8[s:1,a:1]>,@5:i32[s:4,a:4],@9:u32[s:4,a:4],@13:u32[s:4,a:4],@17:u32[s:4,a:4]}";
inline constexpr bool Effect_byte_copy_safe = true;

// --- EffectRelativePtr ---
inline constexpr const char EffectRelativePtr_layout[] =
    "[64-le]record[s:4,a:4]{@0:u32[s:4,a:4]}";
inline constexpr bool EffectRelativePtr_byte_copy_safe = true;

// --- AttributeEntry ---
inline constexpr const char AttributeEntry_layout[] =
    "[64-le]record[s:8,a:4]{@0:u32[s:4,a:4],@4:i32[s:4,a:4]}";
inline constexpr bool AttributeEntry_byte_copy_safe = true;

// ---- Type Registry ----

inline constexpr ::boost::typelayout::TypeEntry types[] = {
    {"UnitSnapshot", UnitSnapshot_layout, UnitSnapshot_byte_copy_safe},
    {"Effect", Effect_layout, Effect_byte_copy_safe},
    {"EffectRelativePtr", EffectRelativePtr_layout, EffectRelativePtr_byte_copy_safe},
    {"AttributeEntry", AttributeEntry_layout, AttributeEntry_byte_copy_safe},
};

inline constexpr std::size_t type_count = 4;

// ---- Platform Info Accessor ----

inline constexpr ::boost::typelayout::PlatformInfo get_platform_info() {
    return { platform_name, arch_prefix, types, type_count,
             pointer_size, sizeof_long, sizeof_wchar_t,
             sizeof_long_double, max_align, data_model };
}

}}}} // namespace boost::typelayout::platform::unit_producer_packed

#endif // BOOST_TYPELAYOUT_SIG_UNIT_PRODUCER_PACKED_HPP
