// AUTO-GENERATED by Boost.TypeLayout Signature Export Tool
// Platform: arm64_macos_clang (AArch64 macOS (Clang))
// Generated: 2026-02-08T03:25:00Z
//
// This file contains constexpr signature data and can be compiled
// by any C++17 or later compiler. P2996 is NOT required.
//
// ABI characteristics (ARM64 macOS, Apple Clang with P2996):
//   - Data model: LP64 (long = 8 bytes)
//   - wchar_t: 4 bytes (same as Linux)
//   - long double: 8 bytes (== double, unlike x86_64 Linux where it's 16)
//   - pointer: 8 bytes
//   - max_align_t: 16 bytes

#ifndef BOOST_TYPELAYOUT_SIG_ARM64_MACOS_CLANG_HPP
#define BOOST_TYPELAYOUT_SIG_ARM64_MACOS_CLANG_HPP

#include <cstddef>

namespace boost { namespace typelayout { namespace platform {
namespace arm64_macos_clang {

// ---- Platform Metadata ----

inline constexpr const char platform_name[] = "arm64_macos_clang";
inline constexpr const char arch_prefix[] = "[64-le]";
inline constexpr std::size_t pointer_size      = 8;
inline constexpr std::size_t sizeof_long        = 8;   // LP64: same as Linux
inline constexpr std::size_t sizeof_wchar_t     = 4;   // same as Linux
inline constexpr std::size_t sizeof_long_double = 8;   // ARM64: long double == double
inline constexpr std::size_t max_align          = 16;

// ---- Type Signatures ----

// --- PacketHeader --- (SAME: all fixed-width types)
inline constexpr const char PacketHeader_layout[] =
    "[64-le]record[s:16,a:4]{@0:u32[s:4,a:4],@4:u16[s:2,a:2],@6:u16[s:2,a:2],@8:u32[s:4,a:4],@12:u32[s:4,a:4]}";
inline constexpr const char PacketHeader_definition[] =
    "[64-le]record[s:16,a:4]{@0[magic]:u32[s:4,a:4],@4[version]:u16[s:2,a:2],@6[type]:u16[s:2,a:2],@8[payload_len]:u32[s:4,a:4],@12[checksum]:u32[s:4,a:4]}";

// --- SharedMemRegion --- (SAME: all fixed-width types)
inline constexpr const char SharedMemRegion_layout[] =
    "[64-le]record[s:24,a:8]{@0:u64[s:8,a:8],@8:u64[s:8,a:8],@16:u32[s:4,a:4],@20:u32[s:4,a:4]}";
inline constexpr const char SharedMemRegion_definition[] =
    "[64-le]record[s:24,a:8]{@0[offset]:u64[s:8,a:8],@8[size]:u64[s:8,a:8],@16[flags]:u32[s:4,a:4],@20[owner_pid]:u32[s:4,a:4]}";

// --- FileHeader --- (SAME: char[], uint32_t, uint64_t)
inline constexpr const char FileHeader_layout[] =
    "[64-le]record[s:24,a:8]{@0:bytes[s:4,a:1],@4:u32[s:4,a:4],@8:u64[s:8,a:8],@16:u32[s:4,a:4],@20:u32[s:4,a:4]}";
inline constexpr const char FileHeader_definition[] =
    "[64-le]record[s:24,a:8]{@0[magic]:bytes[s:4,a:1],@4[version]:u32[s:4,a:4],@8[timestamp]:u64[s:8,a:8],@16[entry_count]:u32[s:4,a:4],@20[reserved]:u32[s:4,a:4]}";

// --- SensorRecord --- (SAME: uint64_t, float, uint32_t)
inline constexpr const char SensorRecord_layout[] =
    "[64-le]record[s:24,a:8]{@0:u64[s:8,a:8],@8:f32[s:4,a:4],@12:f32[s:4,a:4],@16:f32[s:4,a:4],@20:u32[s:4,a:4]}";
inline constexpr const char SensorRecord_definition[] =
    "[64-le]record[s:24,a:8]{@0[timestamp_ns]:u64[s:8,a:8],@8[temperature]:f32[s:4,a:4],@12[humidity]:f32[s:4,a:4],@16[pressure]:f32[s:4,a:4],@20[sensor_id]:u32[s:4,a:4]}";

// --- IpcCommand --- (SAME: all fixed-width types + char[])
inline constexpr const char IpcCommand_layout[] =
    "[64-le]record[s:88,a:8]{@0:u32[s:4,a:4],@4:u32[s:4,a:4],@8:i64[s:8,a:8],@16:i64[s:8,a:8],@24:bytes[s:64,a:1]}";
inline constexpr const char IpcCommand_definition[] =
    "[64-le]record[s:88,a:8]{@0[cmd_id]:u32[s:4,a:4],@4[flags]:u32[s:4,a:4],@8[arg1]:i64[s:8,a:8],@16[arg2]:i64[s:8,a:8],@24[payload]:bytes[s:64,a:1]}";

// --- UnsafeStruct --- (DIFFER: long double = 8B on ARM64 macOS vs 16B on x86_64 Linux)
//
// ARM64 macOS layout:
//   @0:  long        a   = i64[s:8,a:8]       (same as Linux: long=8B on both LP64)
//   @8:  void*       ptr = ptr[s:8,a:8]        (same: pointer=8B)
//   @16: wchar_t     wc  = wchar[s:4,a:4]      (same: wchar_t=4B on both)
//   @20: 4 bytes padding (align to 8 for long double)
//   @24: long double ld  = f80[s:8,a:8]        (DIFFERENT: 8B on ARM64 vs 16B on x86_64)
//   Total: 32 bytes, align 8
//
// x86_64 Linux layout:
//   @0:  long=8, @8: ptr=8, @16: wchar=4, pad to 16-align, @32: long double=16
//   Total: 48 bytes, align 16
inline constexpr const char UnsafeStruct_layout[] =
    "[64-le]record[s:32,a:8]{@0:i64[s:8,a:8],@8:ptr[s:8,a:8],@16:wchar[s:4,a:4],@24:f80[s:8,a:8]}";
inline constexpr const char UnsafeStruct_definition[] =
    "[64-le]record[s:32,a:8]{@0[a]:i64[s:8,a:8],@8[ptr]:ptr[s:8,a:8],@16[wc]:wchar[s:4,a:4],@24[ld]:f80[s:8,a:8]}";

// --- UnsafeWithPointer --- (SAME: uint32_t, ptr, uint64_t — pointer is 8B on both)
inline constexpr const char UnsafeWithPointer_layout[] =
    "[64-le]record[s:24,a:8]{@0:u32[s:4,a:4],@8:ptr[s:8,a:8],@16:u64[s:8,a:8]}";
inline constexpr const char UnsafeWithPointer_definition[] =
    "[64-le]record[s:24,a:8]{@0[id]:u32[s:4,a:4],@8[name]:ptr[s:8,a:8],@16[timestamp]:u64[s:8,a:8]}";

// --- MixedSafety --- (SAME: uint32_t, double, int — all identical on LP64)
inline constexpr const char MixedSafety_layout[] =
    "[64-le]record[s:24,a:8]{@0:u32[s:4,a:4],@8:f64[s:8,a:8],@16:i32[s:4,a:4]}";
inline constexpr const char MixedSafety_definition[] =
    "[64-le]record[s:24,a:8]{@0[id]:u32[s:4,a:4],@8[value]:f64[s:8,a:8],@16[count]:i32[s:4,a:4]}";

// ---- Type Registry (for runtime iteration) ----

struct TypeEntry {
    const char* name;
    const char* layout_sig;
    const char* definition_sig;
};

inline constexpr TypeEntry types[] = {
    {"PacketHeader", PacketHeader_layout, PacketHeader_definition},
    {"SharedMemRegion", SharedMemRegion_layout, SharedMemRegion_definition},
    {"FileHeader", FileHeader_layout, FileHeader_definition},
    {"SensorRecord", SensorRecord_layout, SensorRecord_definition},
    {"IpcCommand", IpcCommand_layout, IpcCommand_definition},
    {"UnsafeStruct", UnsafeStruct_layout, UnsafeStruct_definition},
    {"UnsafeWithPointer", UnsafeWithPointer_layout, UnsafeWithPointer_definition},
    {"MixedSafety", MixedSafety_layout, MixedSafety_definition},
};

inline constexpr int type_count = 8;

}}}} // namespace boost::typelayout::platform::arm64_macos_clang

#endif // BOOST_TYPELAYOUT_SIG_ARM64_MACOS_CLANG_HPP
