// AUTO-GENERATED by Boost.TypeLayout Signature Export Tool
// Platform: x86_64_linux_clang (x86-64 Linux (Clang))
// Generated: 2026-02-08T03:20:57Z
//
// This file contains constexpr signature data and can be compiled
// by any C++17 or later compiler. P2996 is NOT required.

#ifndef BOOST_TYPELAYOUT_SIG_X86_64_LINUX_CLANG_HPP
#define BOOST_TYPELAYOUT_SIG_X86_64_LINUX_CLANG_HPP

#include <boost/typelayout/tools/sig_types.hpp>

namespace boost { namespace typelayout { namespace platform {
namespace x86_64_linux_clang {

// ---- Platform Metadata ----

inline constexpr const char platform_name[] = "x86_64_linux_clang";
inline constexpr const char arch_prefix[] = "[64-le]";
inline constexpr std::size_t pointer_size      = 8;
inline constexpr std::size_t sizeof_long        = 8;
inline constexpr std::size_t sizeof_wchar_t     = 4;
inline constexpr std::size_t sizeof_long_double = 16;
inline constexpr std::size_t max_align          = 16;

// ---- Type Signatures ----

// --- PacketHeader ---
inline constexpr const char PacketHeader_layout[] =
    "[64-le]record[s:16,a:4]{@0:u32[s:4,a:4],@4:u16[s:2,a:2],@6:u16[s:2,a:2],@8:u32[s:4,a:4],@12:u32[s:4,a:4]}";

// --- SharedMemRegion ---
inline constexpr const char SharedMemRegion_layout[] =
    "[64-le]record[s:24,a:8]{@0:u64[s:8,a:8],@8:u64[s:8,a:8],@16:u32[s:4,a:4],@20:u32[s:4,a:4]}";

// --- FileHeader ---
inline constexpr const char FileHeader_layout[] =
    "[64-le]record[s:24,a:8]{@0:bytes[s:4,a:1],@4:u32[s:4,a:4],@8:u64[s:8,a:8],@16:u32[s:4,a:4],@20:u32[s:4,a:4]}";

// --- SensorRecord ---
inline constexpr const char SensorRecord_layout[] =
    "[64-le]record[s:24,a:8]{@0:u64[s:8,a:8],@8:f32[s:4,a:4],@12:f32[s:4,a:4],@16:f32[s:4,a:4],@20:u32[s:4,a:4]}";

// --- IpcCommand ---
inline constexpr const char IpcCommand_layout[] =
    "[64-le]record[s:88,a:8]{@0:u32[s:4,a:4],@4:u32[s:4,a:4],@8:i64[s:8,a:8],@16:i64[s:8,a:8],@24:bytes[s:64,a:1]}";

// --- UnsafeStruct ---
inline constexpr const char UnsafeStruct_layout[] =
    "[64-le]record[s:48,a:16]{@0:i64[s:8,a:8],@8:ptr[s:8,a:8],@16:wchar[s:4,a:4],@32:f80[s:16,a:16]}";

// --- UnsafeWithPointer ---
inline constexpr const char UnsafeWithPointer_layout[] =
    "[64-le]record[s:24,a:8]{@0:u32[s:4,a:4],@8:ptr[s:8,a:8],@16:u64[s:8,a:8]}";

// --- MixedSafety ---
inline constexpr const char MixedSafety_layout[] =
    "[64-le]record[s:24,a:8]{@0:u32[s:4,a:4],@8:f64[s:8,a:8],@16:i32[s:4,a:4]}";

// ---- Type Registry ----

inline constexpr ::boost::typelayout::TypeEntry types[] = {
    {"PacketHeader", PacketHeader_layout},
    {"SharedMemRegion", SharedMemRegion_layout},
    {"FileHeader", FileHeader_layout},
    {"SensorRecord", SensorRecord_layout},
    {"IpcCommand", IpcCommand_layout},
    {"UnsafeStruct", UnsafeStruct_layout},
    {"UnsafeWithPointer", UnsafeWithPointer_layout},
    {"MixedSafety", MixedSafety_layout},
};

inline constexpr int type_count = 8;

// ---- Platform Info Accessor ----

inline constexpr ::boost::typelayout::PlatformInfo get_platform_info() {
    return { platform_name, arch_prefix, types, type_count,
             pointer_size, sizeof_long, sizeof_wchar_t,
             sizeof_long_double, max_align };
}

}}}} // namespace boost::typelayout::platform::x86_64_linux_clang

#endif // BOOST_TYPELAYOUT_SIG_X86_64_LINUX_CLANG_HPP
