// AUTO-GENERATED by Boost.TypeLayout Signature Export Tool
// Platform: x86_64_windows_msvc (x86-64 Windows (MSVC))
// Generated: 2026-02-08T03:21:00Z
//
// This file contains constexpr signature data.
//
// NOTE: This is a simulated signature file representing the expected
// output on x86_64 Windows (MSVC) based on known LLP64 data model
// differences: sizeof(long)=4, sizeof(wchar_t)=2, sizeof(long double)=8.
// Safe types (using only fixed-width integers and float/double) will have
// identical signatures to x86_64 Linux. Unsafe types will differ.

#ifndef BOOST_TYPELAYOUT_SIG_X86_64_WINDOWS_MSVC_HPP
#define BOOST_TYPELAYOUT_SIG_X86_64_WINDOWS_MSVC_HPP

#include <boost/typelayout/tools/sig_types.hpp>

namespace boost { namespace typelayout { namespace platform {
namespace x86_64_windows_msvc {

// ---- Platform Metadata ----

inline constexpr const char platform_name[] = "x86_64_windows_msvc";
inline constexpr const char arch_prefix[] = "[64-le]";
inline constexpr std::size_t pointer_size      = 8;
inline constexpr std::size_t sizeof_long        = 4;   // LLP64: long is 4 bytes
inline constexpr std::size_t sizeof_wchar_t     = 2;   // Windows: wchar_t is 2 bytes
inline constexpr std::size_t sizeof_long_double = 8;   // MSVC: long double == double
inline constexpr std::size_t max_align          = 16;
inline constexpr const char data_model[]        = "LLP64";

// ---- Type Signatures ----

// --- PacketHeader --- (SAME: all fixed-width types)
inline constexpr const char PacketHeader_layout[] =
    "[64-le]record[s:16,a:4]{@0:u32[s:4,a:4],@4:u16[s:2,a:2],@6:u16[s:2,a:2],@8:u32[s:4,a:4],@12:u32[s:4,a:4]}";

// --- SharedMemRegion --- (SAME: all fixed-width types)
inline constexpr const char SharedMemRegion_layout[] =
    "[64-le]record[s:24,a:8]{@0:u64[s:8,a:8],@8:u64[s:8,a:8],@16:u32[s:4,a:4],@20:u32[s:4,a:4]}";

// --- FileHeader --- (SAME: char[], uint32_t, uint64_t)
inline constexpr const char FileHeader_layout[] =
    "[64-le]record[s:24,a:8]{@0:bytes[s:4,a:1],@4:u32[s:4,a:4],@8:u64[s:8,a:8],@16:u32[s:4,a:4],@20:u32[s:4,a:4]}";

// --- SensorRecord --- (SAME: uint64_t, float, uint32_t)
inline constexpr const char SensorRecord_layout[] =
    "[64-le]record[s:24,a:8]{@0:u64[s:8,a:8],@8:f32[s:4,a:4],@12:f32[s:4,a:4],@16:f32[s:4,a:4],@20:u32[s:4,a:4]}";

// --- IpcCommand --- (SAME: all fixed-width types + char[])
inline constexpr const char IpcCommand_layout[] =
    "[64-le]record[s:88,a:8]{@0:u32[s:4,a:4],@4:u32[s:4,a:4],@8:i64[s:8,a:8],@16:i64[s:8,a:8],@24:bytes[s:64,a:1]}";

// --- UnsafeStruct --- (DIFFER: long=4B, wchar_t=2B, long double=8B on Windows)
// Linux:   record[s:48,a:16]{@0:i64[s:8,a:8],@8:ptr[s:8,a:8],@16:wchar[s:4,a:4],@32:fld[s:16,a:16]}
// Windows: record[s:32,a:8]{@0:i32[s:4,a:4],@8:ptr[s:8,a:8],@16:wchar[s:2,a:2],@24:fld[s:8,a:8]}
inline constexpr const char UnsafeStruct_layout[] =
    "[64-le]record[s:32,a:8]{@0:i32[s:4,a:4],@8:ptr[s:8,a:8],@16:wchar[s:2,a:2],@24:fld[s:8,a:8]}";

// --- UnsafeWithPointer --- (SAME: uint32_t, ptr, uint64_t — pointer is 8B on both)
inline constexpr const char UnsafeWithPointer_layout[] =
    "[64-le]record[s:24,a:8]{@0:u32[s:4,a:4],@8:ptr[s:8,a:8],@16:u64[s:8,a:8]}";

// --- MixedSafety --- (SAME: uint32_t, double, int — int is 4B on both x86_64 platforms)
inline constexpr const char MixedSafety_layout[] =
    "[64-le]record[s:24,a:8]{@0:u32[s:4,a:4],@8:f64[s:8,a:8],@16:i32[s:4,a:4]}";

// ---- Type Registry ----


inline constexpr ::boost::typelayout::TypeEntry types[] = {
    {"PacketHeader", PacketHeader_layout},
    {"SharedMemRegion", SharedMemRegion_layout},
    {"FileHeader", FileHeader_layout},
    {"SensorRecord", SensorRecord_layout},
    {"IpcCommand", IpcCommand_layout},
    {"UnsafeStruct", UnsafeStruct_layout},
    {"UnsafeWithPointer", UnsafeWithPointer_layout},
    {"MixedSafety", MixedSafety_layout},
};

inline constexpr std::size_t type_count = 8;

// ---- Platform Info Accessor ----

inline constexpr ::boost::typelayout::PlatformInfo get_platform_info() {
    return { platform_name, arch_prefix, types, type_count,
             pointer_size, sizeof_long, sizeof_wchar_t,
             sizeof_long_double, max_align, data_model };
}

}}}} // namespace boost::typelayout::platform::x86_64_windows_msvc

#endif // BOOST_TYPELAYOUT_SIG_X86_64_WINDOWS_MSVC_HPP
