// Copyright (c) 2024-2026 TypeLayout Development Team
// Distributed under the Boost Software License, Version 1.0.
//
// Signature computation engine: Layout mode (flattened byte identity)
// and union layout helpers.
//
// =========================================================================
// Signature Grammar (BNF)
// =========================================================================
//
// A layout signature is a self-describing string encoding the byte-level
// identity of a C++ type.  The grammar below defines the syntax.
//
//   full-signature ::= arch-prefix type-signature
//
//   arch-prefix    ::= '[' pointer-bits '-' endianness ']'
//   pointer-bits   ::= '32' | '64'
//   endianness     ::= 'le' | 'be'
//
//   type-signature ::= leaf-signature | record-signature | union-signature
//                     | enum-signature | array-signature | opaque-signature
//
//   leaf-signature ::= type-kind '[' params ']'
//   type-kind      ::= 'i8' | 'i16' | 'i32' | 'i64'
//                     | 'u8' | 'u16' | 'u32' | 'u64'
//                     | 'f32' | 'f64' | 'f80'
//                     | 'char' | 'wchar' | 'char8' | 'char16' | 'char32'
//                     | 'bool' | 'byte' | 'nullptr'
//                     | 'ptr' | 'fnptr' | 'memptr' | 'ref' | 'rref'
//
//   params         ::= param (',' param)*
//   param          ::= key ':' value
//   key            ::= 's' | 'a'
//   value          ::= DIGIT+
//
//   record-signature ::= 'record' '[' params ']' '{' member-list '}'
//   union-signature  ::= 'union'  '[' params ']' '{' member-list '}'
//   member-list      ::= '' | member (',' member)*
//   member           ::= '@' offset ':' type-signature
//                       | '@' offset '.' bit-offset ':' bitfield-entry
//   offset           ::= DIGIT+
//   bit-offset       ::= DIGIT+
//   bitfield-entry   ::= 'bits<' bit-width ',' leaf-signature '>'
//   bit-width        ::= DIGIT+
//
//   enum-signature   ::= 'enum' '[' params ']' '<' type-signature '>'
//   array-signature  ::= 'array' '[' params ']' '<' type-signature ',' count '>'
//                       | 'bytes' '[' params ']'
//   count            ::= DIGIT+
//
//   opaque-signature ::= 'O(' TAG '|' size '|' alignment ')'
//   TAG              ::= [^|)]+
//   size             ::= DIGIT+
//   alignment        ::= DIGIT+
//
// Notes:
//   - Empty classes embedded as base (EBO) or [[no_unique_address]] member
//     use s:0 in the host signature.  Standalone signatures use s:1.
//   - DIGIT ::= [0-9]
//
// =========================================================================

#ifndef BOOST_TYPELAYOUT_DETAIL_SIGNATURE_IMPL_HPP
#define BOOST_TYPELAYOUT_DETAIL_SIGNATURE_IMPL_HPP

#include <boost/typelayout/detail/reflect.hpp>

namespace boost {
namespace typelayout {

    // =========================================================================
    // Layout Signature Engine
    // =========================================================================

    // Detect whether a type has a custom (non-default) TypeSignature
    // specialization, such as those generated by TYPELAYOUT_OPAQUE_* macros.
    // Opaque specializations define `static constexpr bool is_opaque = true`.
    template <typename T>
    concept has_opaque_signature = requires {
        { TypeSignature<std::remove_cv_t<T>>::is_opaque } -> std::convertible_to<bool>;
    } && TypeSignature<std::remove_cv_t<T>>::is_opaque;

    // Helper: generate an "embedded" signature for an empty type.
    //
    // When an empty class is used as a base (EBO) or as a
    // [[no_unique_address]] member, it occupies 0 bytes in the host
    // layout.  The standalone TypeSignature<Empty>::calculate() still
    // returns s:1 (per C++ standard: sizeof(Empty) == 1), but the
    // embedded version must report s:0 to accurately reflect the
    // host's byte layout.
    //
    // This function takes the standalone signature and patches its
    // "s:N" field to "s:0".  For a typical empty class, the standalone
    // signature is "record[s:1,a:1]{}" and the embedded version becomes
    // "record[s:0,a:1]{}".
    template <typename T>
    consteval auto embedded_empty_signature() noexcept {
        static constexpr auto full = TypeSignature<T>::calculate();
        // Find "[s:" and replace the size value with "0".
        // Format: ...kind[s:SIZE,a:ALIGN]...
        // We rebuild: prefix + "[s:0" + rest_from_comma
        constexpr auto str = std::string_view(full);
        constexpr auto s_pos = str.find("[s:");
        static_assert(s_pos != std::string_view::npos,
            "embedded_empty_signature: expected [s: in signature");
        // Find the comma after the size digits
        constexpr auto comma_pos = str.find(',', s_pos + 3);
        static_assert(comma_pos != std::string_view::npos,
            "embedded_empty_signature: expected comma after size");
        // Build: prefix_up_to_bracket + "[s:0" + rest_from_comma
        return FixedString<s_pos>(str.substr(0, s_pos)) +
               FixedString{"[s:0"} +
               FixedString<str.size() - comma_pos>(str.substr(comma_pos));
    }

    // Every helper returns a comma-PREFIXED string. The top-level function
    // strips the leading comma via skip_first().

    template <typename T, std::size_t OffsetAdj>
    consteval auto layout_all_prefixed() noexcept;

    template<typename T, std::size_t Index, std::size_t OffsetAdj>
    consteval auto layout_field_with_comma() noexcept {
        using namespace std::meta;
        constexpr auto member = nonstatic_data_members_of(^^T, access_context::unchecked())[Index];
        using FieldType = [:type_of(member):];

        if constexpr (is_bit_field(member)) {
            // Full precision: emit @byte.bit:bits<width,type>
            constexpr auto bit_off = offset_of(member);
            constexpr std::size_t byte_pos = bit_off.bytes + OffsetAdj;
            constexpr std::size_t bit_pos  = bit_off.bits;
            constexpr std::size_t bwidth   = bit_size_of(member);
            return FixedString{",@"} +
                   to_fixed_string<byte_pos>() +
                   FixedString{"."} +
                   to_fixed_string<bit_pos>() +
                   FixedString{":bits<"} +
                   to_fixed_string<bwidth>() +
                   FixedString{","} +
                   TypeSignature<FieldType>::calculate() +
                   FixedString{">"};
        } else if constexpr (std::is_class_v<FieldType> && !std::is_union_v<FieldType>
                             && !has_opaque_signature<FieldType>
                             && !std::is_empty_v<FieldType>) {
            // Non-opaque, non-empty class: recursively flatten into parent layout.
            constexpr std::size_t field_offset = offset_of(member).bytes + OffsetAdj;
            return layout_all_prefixed<FieldType, field_offset>();
        } else if constexpr (std::is_empty_v<FieldType>
                             && std::is_class_v<FieldType>
                             && !has_opaque_signature<FieldType>) {
            // Empty member (possibly [[no_unique_address]]): occupies 0 bytes
            // in the host layout.  Use embedded_empty_signature to patch s:0,
            // consistent with the EBO handling in layout_one_base_prefixed.
            constexpr std::size_t emb_off = offset_of(member).bytes + OffsetAdj;
            return FixedString{",@"} +
                   to_fixed_string<emb_off>() +
                   FixedString{":"} +
                   embedded_empty_signature<FieldType>();
        } else {
            // Primitive, union, enum, opaque class, or any type with a
            // custom TypeSignature specialization: emit as a leaf node.
            constexpr std::size_t leaf_off = offset_of(member).bytes + OffsetAdj;
            return FixedString{",@"} +
                   to_fixed_string<leaf_off>() +
                   FixedString{":"} +
                   TypeSignature<FieldType>::calculate();
        }
    }

    template <typename T, std::size_t OffsetAdj, std::size_t... Is>
    consteval auto layout_direct_fields_prefixed(std::index_sequence<Is...>) noexcept {
        if constexpr (sizeof...(Is) == 0) return FixedString{""};
        else return (layout_field_with_comma<T, Is, OffsetAdj>() + ...);
    }

    template <typename T, std::size_t BaseIndex, std::size_t OffsetAdj>
    consteval auto layout_one_base_prefixed() noexcept {
        using namespace std::meta;
        constexpr auto base_info = bases_of(^^T, access_context::unchecked())[BaseIndex];
        using BaseType = [:type_of(base_info):];
        if constexpr (std::is_empty_v<BaseType>) {
            // Empty base: EBO makes it occupy 0 bytes.  Use
            // embedded_empty_signature to emit s:0 in the host signature.
            constexpr std::size_t base_emb_off = offset_of(base_info).bytes + OffsetAdj;
            return FixedString{",@"} +
                   to_fixed_string<base_emb_off>() +
                   FixedString{":"} +
                   embedded_empty_signature<BaseType>();
        } else if constexpr (has_opaque_signature<BaseType>) {
            // Opaque base: emit as leaf node at base offset, not flattened.
            constexpr std::size_t base_opq_off = offset_of(base_info).bytes + OffsetAdj;
            return FixedString{",@"} +
                   to_fixed_string<base_opq_off>() +
                   FixedString{":"} +
                   TypeSignature<BaseType>::calculate();
        } else {
            return layout_all_prefixed<BaseType, offset_of(base_info).bytes + OffsetAdj>();
        }
    }

    template <typename T, std::size_t OffsetAdj, std::size_t... Is>
    consteval auto layout_bases_prefixed(std::index_sequence<Is...>) noexcept {
        if constexpr (sizeof...(Is) == 0) return FixedString{""};
        else return (layout_one_base_prefixed<T, Is, OffsetAdj>() + ...);
    }

    template <typename T, std::size_t OffsetAdj>
    consteval auto layout_all_prefixed() noexcept {
        static_assert(!has_virtual_base<T>(),
            "TypeLayout: types with virtual inheritance are not supported. "
            "Virtual bases introduce hidden vbptrs whose layout is "
            "compiler-specific, and diamond inheritance causes the "
            "flattening engine to double-count the shared virtual base.");
        constexpr std::size_t bc = get_base_count<T>();
        constexpr std::size_t fc = get_member_count<T>();
        if constexpr (bc == 0 && fc == 0) return FixedString{""};
        else if constexpr (bc == 0) return layout_direct_fields_prefixed<T, OffsetAdj>(std::make_index_sequence<fc>{});
        else if constexpr (fc == 0) return layout_bases_prefixed<T, OffsetAdj>(std::make_index_sequence<bc>{});
        else return layout_bases_prefixed<T, OffsetAdj>(std::make_index_sequence<bc>{}) +
                    layout_direct_fields_prefixed<T, OffsetAdj>(std::make_index_sequence<fc>{});
    }

    template <typename T>
    consteval auto get_layout_content() noexcept {
        return layout_all_prefixed<T, 0>().skip_first();
    }

    // =========================================================================
    // Union Layout Helpers (no flattening)
    // =========================================================================

    template<typename T, std::size_t Index>
    consteval auto layout_union_field() noexcept {
        using namespace std::meta;
        constexpr auto member = nonstatic_data_members_of(^^T, access_context::unchecked())[Index];
        using FieldType = [:type_of(member):];

        if constexpr (is_bit_field(member)) {
            constexpr auto bit_off = offset_of(member);
            constexpr std::size_t ubyte_pos = bit_off.bytes;
            constexpr std::size_t ubit_pos  = bit_off.bits;
            constexpr std::size_t ubwidth   = bit_size_of(member);
            return FixedString{"@"} +
                   to_fixed_string<ubyte_pos>() +
                   FixedString{"."} +
                   to_fixed_string<ubit_pos>() +
                   FixedString{":bits<"} +
                   to_fixed_string<ubwidth>() +
                   FixedString{","} +
                   TypeSignature<FieldType>::calculate() +
                   FixedString{">"};
        } else {
            constexpr std::size_t uf_off = offset_of(member).bytes;
            return FixedString{"@"} +
                   to_fixed_string<uf_off>() +
                   FixedString{":"} +
                   TypeSignature<FieldType>::calculate();
        }
    }

    template<typename T, std::size_t Index, bool IsFirst>
    consteval auto layout_union_field_with_comma() noexcept {
        if constexpr (IsFirst)
            return layout_union_field<T, Index>();
        else
            return FixedString{","} + layout_union_field<T, Index>();
    }

    template<typename T, std::size_t... Is>
    consteval auto concatenate_layout_union_fields(std::index_sequence<Is...>) noexcept {
        return (layout_union_field_with_comma<T, Is, (Is == 0)>() + ...);
    }

    template <typename T>
    consteval auto get_layout_union_content() noexcept {
        constexpr std::size_t count = get_member_count<T>();
        if constexpr (count == 0)
            return FixedString{""};
        else
            return concatenate_layout_union_fields<T>(std::make_index_sequence<count>{});
    }

} // namespace typelayout
} // namespace boost

#endif // BOOST_TYPELAYOUT_DETAIL_SIGNATURE_IMPL_HPP