// AUTO-GENERATED by Boost.TypeLayout Signature Export Tool
// Platform: producer_packed (producer_packed)
// Generated: 2026-08-27T16:36:10Z
//
// This file contains constexpr signature data.

#ifndef BOOST_TYPELAYOUT_SIG_PRODUCER_PACKED_HPP
#define BOOST_TYPELAYOUT_SIG_PRODUCER_PACKED_HPP

#include <boost/typelayout/tools/sig_types.hpp>

namespace boost { namespace typelayout { namespace platform {
namespace producer_packed {

// ---- Platform Metadata ----

inline constexpr const char platform_name[] = "producer_packed";
inline constexpr const char arch_prefix[] = "[64-le]";
inline constexpr std::size_t pointer_size      = 8;
inline constexpr std::size_t sizeof_long        = 8;
inline constexpr std::size_t sizeof_wchar_t     = 4;
inline constexpr std::size_t sizeof_long_double = 16;
inline constexpr std::size_t max_align          = 16;
inline constexpr const char data_model[]        = "LP64";

// ---- Type Signatures ----

// --- WorldSnapshot ---
inline constexpr const char WorldSnapshot_layout[] =
    "[64-le]record[s:40,a:8]{@0:u64[s:8,a:8],@8:u32[s:4,a:4],@12:u32[s:4,a:4],@16:u32[s:4,a:4],@20:u32[s:4,a:4],@24:u32[s:4,a:4],@28:u32[s:4,a:4],@32:u32[s:4,a:4]}";
inline constexpr bool WorldSnapshot_byte_copy_safe = true;

// --- Entity ---
inline constexpr const char Entity_layout[] =
    "[64-le]record[s:37,a:1]{@0:u64[s:8,a:8],@8:enum[s:1,a:1]<u8[s:1,a:1]>,@9:i32[s:4,a:4],@13:i32[s:4,a:4],@17:i32[s:4,a:4],@21:u32[s:4,a:4],@25:u32[s:4,a:4],@29:u32[s:4,a:4],@33:u32[s:4,a:4]}";
inline constexpr bool Entity_byte_copy_safe = true;

// --- EntityRelativePtr ---
inline constexpr const char EntityRelativePtr_layout[] =
    "[64-le]record[s:4,a:4]{@0:u32[s:4,a:4]}";
inline constexpr bool EntityRelativePtr_byte_copy_safe = true;

// --- EntityIndexEntry ---
inline constexpr const char EntityIndexEntry_layout[] =
    "[64-le]record[s:16,a:8]{@0:u64[s:8,a:8],@8:u32[s:4,a:4]}";
inline constexpr bool EntityIndexEntry_byte_copy_safe = true;

// ---- Type Registry ----

inline constexpr ::boost::typelayout::TypeEntry types[] = {
    {"WorldSnapshot", WorldSnapshot_layout, WorldSnapshot_byte_copy_safe},
    {"Entity", Entity_layout, Entity_byte_copy_safe},
    {"EntityRelativePtr", EntityRelativePtr_layout, EntityRelativePtr_byte_copy_safe},
    {"EntityIndexEntry", EntityIndexEntry_layout, EntityIndexEntry_byte_copy_safe},
};

inline constexpr std::size_t type_count = 4;

// ---- Platform Info Accessor ----

inline constexpr ::boost::typelayout::PlatformInfo get_platform_info() {
    return { platform_name, arch_prefix, types, type_count,
             pointer_size, sizeof_long, sizeof_wchar_t,
             sizeof_long_double, max_align, data_model };
}

}}}} // namespace boost::typelayout::platform::producer_packed

#endif // BOOST_TYPELAYOUT_SIG_PRODUCER_PACKED_HPP
