<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DefineConstants Condition="'$(PublishAot)' == 'true'">$(DefineConstants);LAYOUT_NATIVEAOT</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="Configuration" />
    <ProjectReference Include="../LayoutObserver.Generator/LayoutObserver.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" GlobalPropertiesToRemove="PublishAot;RuntimeIdentifier;SelfContained" />
  </ItemGroup>
</Project>
