// AUTO-GENERATED by Boost.TypeLayout Signature Export Tool
// Platform: arm64_macos_clang (AArch64 macOS (Clang))
// Generated: 2026-02-08T03:25:00Z
//
// Green-path reference artifact: safe types only.

#ifndef BOOST_TYPELAYOUT_SIG_ARM64_MACOS_CLANG_GREEN_HPP
#define BOOST_TYPELAYOUT_SIG_ARM64_MACOS_CLANG_GREEN_HPP

#include <boost/typelayout/tools/sig_types.hpp>

namespace boost { namespace typelayout { namespace platform {
namespace arm64_macos_clang {

inline constexpr const char platform_name[] = "arm64_macos_clang";
inline constexpr const char arch_prefix[] = "[64-le]";
inline constexpr std::size_t pointer_size      = 8;
inline constexpr std::size_t sizeof_long       = 8;
inline constexpr std::size_t sizeof_wchar_t    = 4;
inline constexpr std::size_t sizeof_long_double = 8;
inline constexpr std::size_t max_align         = 16;
inline constexpr const char data_model[]       = "LP64";

inline constexpr const char PacketHeader_layout[] =
    "[64-le]record[s:16,a:4]{@0:u32[s:4,a:4],@4:u16[s:2,a:2],@6:u16[s:2,a:2],@8:u32[s:4,a:4],@12:u32[s:4,a:4]}";
inline constexpr bool PacketHeader_byte_copy_safe = true;

inline constexpr const char SharedMemRegion_layout[] =
    "[64-le]record[s:24,a:8]{@0:u64[s:8,a:8],@8:u64[s:8,a:8],@16:u32[s:4,a:4],@20:u32[s:4,a:4]}";
inline constexpr bool SharedMemRegion_byte_copy_safe = true;

inline constexpr const char FileHeader_layout[] =
    "[64-le]record[s:24,a:8]{@0:bytes[s:4,a:1],@4:u32[s:4,a:4],@8:u64[s:8,a:8],@16:u32[s:4,a:4],@20:u32[s:4,a:4]}";
inline constexpr bool FileHeader_byte_copy_safe = true;

inline constexpr const char SensorRecord_layout[] =
    "[64-le]record[s:24,a:8]{@0:u64[s:8,a:8],@8:f32[s:4,a:4],@12:f32[s:4,a:4],@16:f32[s:4,a:4],@20:u32[s:4,a:4]}";
inline constexpr bool SensorRecord_byte_copy_safe = true;

inline constexpr const char IpcCommand_layout[] =
    "[64-le]record[s:88,a:8]{@0:u32[s:4,a:4],@4:u32[s:4,a:4],@8:i64[s:8,a:8],@16:i64[s:8,a:8],@24:bytes[s:64,a:1]}";
inline constexpr bool IpcCommand_byte_copy_safe = true;

inline constexpr const char MixedSafety_layout[] =
    "[64-le]record[s:24,a:8]{@0:u32[s:4,a:4],@8:f64[s:8,a:8],@16:i32[s:4,a:4]}";
inline constexpr bool MixedSafety_byte_copy_safe = true;

inline constexpr ::boost::typelayout::TypeEntry types[] = {
    {"PacketHeader", PacketHeader_layout, PacketHeader_byte_copy_safe},
    {"SharedMemRegion", SharedMemRegion_layout, SharedMemRegion_byte_copy_safe},
    {"FileHeader", FileHeader_layout, FileHeader_byte_copy_safe},
    {"SensorRecord", SensorRecord_layout, SensorRecord_byte_copy_safe},
    {"IpcCommand", IpcCommand_layout, IpcCommand_byte_copy_safe},
    {"MixedSafety", MixedSafety_layout, MixedSafety_byte_copy_safe},
};

inline constexpr std::size_t type_count = 6;

inline constexpr ::boost::typelayout::PlatformInfo get_platform_info() {
    return { platform_name, arch_prefix, types, type_count,
             pointer_size, sizeof_long, sizeof_wchar_t,
             sizeof_long_double, max_align, data_model };
}

}}}} // namespace boost::typelayout::platform::arm64_macos_clang

#endif // BOOST_TYPELAYOUT_SIG_ARM64_MACOS_CLANG_GREEN_HPP
